### ISSUE TITLE
Build Aggregator Lambda Fn

### ISSUE THREAD

**Issue by rnason** [atlanteansoftware/CloudQuery-Issues#5]

**Comment by dsikes** [comment]
Because of the way we are using S3 to serve as our "database" we do not need to aggregate the data. Using an accessory file, you can create as complex of a query as you want, and the results from that query are provided as a dictionary for the template. The original reason for this issue has been resolved, so I am closing this. However, if we want to aggregate the data for other reason in the future, we can revisit this.
